### ISSUE TITLE
error messages

### ISSUE THREAD

**Issue by rubydesign** [posiczko/devise-tailwindcssed#18]
Hi, really great, saved hours. Let me buy you a coffee.

I think devise moved to a error message template. Instead of the helper.
Easier to customize.

And i found myself putting a flex.justify-center around all templates. But that's maybe just me, my layout yields in the body.

Still, great, thanks

**Comment by rubydesign** [comment]
Sorry, it's not just the error message that seem outdated, but the all urls.

**Comment by didierganthier** [comment]
All of my styles are being applied but not the one for the error message. How can I handle this? This is what my error message looks like 👇🏽 
![Screenshot 2023-02-13 at 20 23 04](https://user-images.githubusercontent.com/45739963/218613781-95f60af4-7d6a-468b-bfcc-0a35ee4a7fe7.png)

**Comment by scottrobertson** [comment]
> All of my styles are being applied but not the one for the error message. @PabloC @scottrobertson @posiczko @danieldenis01 how can I handle this? This is what my error message looks like 👇🏽 
> 
> ![Screenshot 2023-02-13 at 20 23 04](https://user-images.githubusercontent.com/45739963/218613781-95f60af4-7d6a-468b-bfcc-0a35ee4a7fe7.png)

Pleas don't tag all collaborators like this.

**Comment by didierganthier** [comment]
> > All of my styles are being applied but not the one for the error message. @PabloC @scottrobertson @posiczko @danieldenis01 how can I handle this? This is what my error message looks like 👇🏽
> > ![Screenshot 2023-02-13 at 20 23 04](https://user-images.githubusercontent.com/45739963/218613781-95f60af4-7d6a-468b-bfcc-0a35ee4a7fe7.png)
> 
> Pleas don't tag all collaborators like this.

I've just been going through these for hours and it seems like a simple task to me, sorry for tagging all collaborators but any idea why my styles aren't being applied?

**Comment by scottrobertson** [comment]
> > > ![Screenshot 2023-02-13 at 20 23 04](https://user-images.githubusercontent.com/45739963/218613781-95f60af4-7d6a-468b-bfcc-0a35ee4a7fe7.png)
> 
> > 
> 
> > Pleas don't tag all collaborators like this.
> 
> 
> 
> I've just been going through these for hours and it seems like a simple task to me, sorry for tagging all collaborators but any idea why my styles aren't being applied?

No clue. All I've ever done here is fix a typo. This is why you shouldn't do what you did.

**Comment by didierganthier** [comment]
> > > > ![Screenshot 2023-02-13 at 20 23 04](https://user-images.githubusercontent.com/45739963/218613781-95f60af4-7d6a-468b-bfcc-0a35ee4a7fe7.png)
> > 
> > 
> > > 
> > 
> > 
> > > Pleas don't tag all collaborators like this.
> > 
> > 
> > I've just been going through these for hours and it seems like a simple task to me, sorry for tagging all collaborators but any idea why my styles aren't being applied?
> 
> No clue. All I've ever done here is fix a typo. This is why you shouldn't do what you did.

Oh my bad, I didn't know. That makes no difference but I removed the tags, my sincere apologies. 🙂

**Comment by rubydesign** [comment]
@didierganthier you have to change the devise error template ./app/views/devise/shared/_error_messages.html.haml (or erb if you use erb) 
You can see in the devise docs how to install the templates. 

I shall close this as it is all noise now
