### ISSUE TITLE
Issues with layouts/devise.html.erb

### ISSUE THREAD

**Issue by ranle** [posiczko/devise-tailwindcssed#9]
This gem is great for kickstarting the css for tailwind and devise!
I had an issue that my devise forms would be showing up correctly, but without my default application layout. 
When I deleted layouts/devise.html.erb which this gem generates, the issue was fixed.
Has anyone had the same issue?

I suggest removing the layout file from the gem.

**Comment by danieldenis01** [comment]
I solved this issue through PR #16, removing the template.

**Comment by posiczko** [comment]
Thank you @danieldenis01
